#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/light?useUnicode=yes&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
#    username: light
#    password: 12345
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    sql-script-encoding: UTF-8
